Add a pre-publish check to publish. (#264)
Also add a new `dry-run-publish` command so that we can test the publishing process.

Here is what the command is link and the kinds of warnings that you now get:

```
$ npm run dry-run-publish

> wonder-blocks@0.0.1 dry-run-publish /Users/jeresig/khan/wonder-blocks
> yarn run publish --no-npm --no-git

yarn run v1.7.0
$ node utils/pre-publish-check.js && git diff --stat --exit-code HEAD && yarn build:all && lerna publish --no-npm --no-git
@khanacademy/wonder-blocks-dropdown is private and won't be published to NPM.
@khanacademy/wonder-blocks-form is private and won't be published to NPM.
@khanacademy/wonder-blocks-grid is private and won't be published to NPM.
@khanacademy/wonder-blocks-toolbar is private and won't be published to NPM.
@khanacademy/wonder-blocks-tooltip is private and won't be published to NPM.
? There are some potential problems, do you wish to continue? (Y/n)
```

If you answer "no" then it errors out and stops the publish:

```
$ npm run dry-run-publish

> wonder-blocks@0.0.1 dry-run-publish /Users/jeresig/khan/wonder-blocks
> yarn run publish --no-npm --no-git

yarn run v1.7.0
$ node utils/pre-publish-check.js && git diff --stat --exit-code HEAD && yarn build:all && lerna publish --no-npm --no-git
@khanacademy/wonder-blocks-dropdown is private and won't be published to NPM.
@khanacademy/wonder-blocks-form is private and won't be published to NPM.
@khanacademy/wonder-blocks-grid is private and won't be published to NPM.
@khanacademy/wonder-blocks-toolbar is private and won't be published to NPM.
@khanacademy/wonder-blocks-tooltip is private and won't be published to NPM.
? There are some potential problems, do you wish to continue? No
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wonder-blocks@0.0.1 dry-run-publish: `yarn run publish --no-npm --no-git`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wonder-blocks@0.0.1 dry-run-publish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jeresig/.npm/_logs/2018-08-06T17_43_39_855Z-debug.log
```

Additionally, it checks for the missing publishConfirm and errors out if it doesn't see it:

```
$ npm run dry-run-publish

> wonder-blocks@0.0.1 dry-run-publish /Users/jeresig/khan/wonder-blocks
> yarn run publish --no-npm --no-git

yarn run v1.7.0
$ node utils/pre-publish-check.js && git diff --stat --exit-code HEAD && yarn build:all && lerna publish --no-npm --no-git
ERROR: @khanacademy/wonder-blocks-dropdown is missing a "publishConfig": {"access": "public"} section.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wonder-blocks@0.0.1 dry-run-publish: `yarn run publish --no-npm --no-git`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wonder-blocks@0.0.1 dry-run-publish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jeresig/.npm/_logs/2018-08-06T17_44_33_361Z-debug.log
```

We can add more checks later but these are a couple that've caused issues for me!