[🔥AUDIT🔥] WB Theming: Change package.json to fix changesets issue (#1970)
🖍 _This is an audit!_ 🖍

## Summary:

Switched `publishConfig.access` to `restricted` to fix the following error:

https://github.com/Khan/wonder-blocks/actions/runs/5765545001/job/15631699707#step:5:24

```
ERROR: @khanacademy/wonder-blocks-theming is marked as private but there is a "publishConfig": {"access": "public"} section already defined. Please change it to "access": "restricted" or remove "private": true to make the package public.
error Command failed with exit code 1.
```

This way we can still publish all the WB packages to NPM, except for the theming
package.


Issue: XXX-XXXX

## Test plan:

N/A

Author: jandrade

Auditors: #wonder-blocks

Required Reviewers:

Approved By:

Checks: ✅ codecov/project, ✅ Check build sizes (ubuntu-latest, 16.x), ✅ Lint (ubuntu-latest, 16.x), ✅ Test (ubuntu-latest, 16.x, 2/2), ✅ Test (ubuntu-latest, 16.x, 1/2), ✅ Prime node_modules cache for primary configuration (ubuntu-latest, 16.x), ✅ gerald, ⏭  dependabot, ✅ Chromatic - Build on review PR (push) / chromatic (ubuntu-latest, 16.x), ⏭  Chromatic - Skip on dependabot PRs (push)

Pull Request URL: https://github.com/Khan/wonder-blocks/pull/1970